POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "name": "Thangdeptrai",
    "email": "thangdeptrai@gmail.com",
    "password": "helloworld",
    "role": "admin"
}

###

POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "email": "truongdeptrai@gmail.com",
    "password": "helloworld"
}